# Generated by Django 4.1.4 on 2023-09-19 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail_sizes', models.CharField(help_text="Comma-separated list of thumbnail sizes (e.g., '200x200,400x400').", max_length=255)),
                ('generate_expiring_links', models.BooleanField(default=False, help_text='Enable generating expiring links for images.')),
                ('expiring_link_duration', models.PositiveIntegerField(default=300, help_text='Duration in seconds for expiring links (between 300 and 30000 seconds).')),
                ('include_original_link', models.BooleanField(default=False, help_text='Include a link to the originally uploaded image.')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
