# Generated by Django 4.1.4 on 2023-09-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='expiring_link_duration',
        ),
    ]
