# Generated by Django 4.1.4 on 2023-09-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='url',
            new_name='thumbnail',
        ),
    ]
